services:
  db:
    image: postgres:15-alpine
    container_name: go-bank-api-db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always

  api:
    build: .
    container_name: go-bank-api
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env

  migrate:
    image: migrate/migrate
    container_name: go-bank-api-migrate
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./db/migrations:/migrations
    command: [
      "-path=/migrations",
      "-database=postgres://postgres:159357@db:5432/go_bank_api?sslmode=disable",
      "up"
    ]

volumes:
  postgres_data: {}