# file: .github/workflows/ci.yml

name: Go Bank API CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: user_test
          POSTGRES_PASSWORD: password_test
          POSTGRES_DB: go_bank_api_test
        ports:
          - 5434:5432
        options: >-
          --health-cmd "pg_isready -U user_test -d go_bank_api_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      # NEW STEP: Install Swag CLI
      # The swag binary is required to generate the documentation files.
      - name: Install Swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      # NEW STEP: Generate Swagger docs
      # This step creates the 'docs' directory that our code needs to compile.
      - name: Generate docs
        run: swag init -g cmd/main.go

      # FINAL STEP: Run the tests
      - name: Run tests
        env:
          DB_HOST: localhost
          DB_PORT: 5434
          DB_USER: user_test
          DB_PASSWORD: password_test
          DB_NAME: go_bank_api 
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
          PORT: 8080
        run: go test -v ./...