# file: .github/workflows/ci.yml

name: Go Bank API CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    # Set job-level environment variables from secrets.
    # This is a robust way to make secrets available throughout the job.
    env:
      POSTGRES_USER: ${{ secrets.DB_USER }}
      POSTGRES_PASSWORD: ${{ secrets.DB_PASSWORD }}
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}

    services:
      postgres:
        image: postgres:15-alpine
        # Use the job-level environment variables defined above.
        env:
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          POSTGRES_DB: go_bank_api_test
        ports:
          - 5434:5432
        options: >-
          --health-cmd "pg_isready -U ${{ env.POSTGRES_USER }} -d go_bank_api_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Run tests
        # The test step also uses the job-level environment variables.
        # Note that the DB_HOST for a service container is localhost on the mapped port.
        env:
          DB_HOST: localhost
          DB_PORT: 5434
          DB_USER: ${{ env.POSTGRES_USER }}
          DB_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
          DB_NAME: go_bank_api 
          JWT_SECRET_KEY: ${{ env.JWT_SECRET_KEY }}
          PORT: 8080
        run: go test -v ./...