# file: .github/workflows/ci.yml

name: Go Bank API CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: user_test
          POSTGRES_PASSWORD: password_test
          POSTGRES_DB: go_bank_api_test
        ports:
          - 5434:5432
        options: >-
          --health-cmd "pg_isready -U user_test -d go_bank_api_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Install Swag
        run: go install github.com/swaggo/swag/cmd/swag@latest

      - name: Generate docs
        run: swag init -g cmd/main.go

      # CORRECTED STEP: Create a dummy config file with credentials matching the test database service.
      - name: Create config file for tests
        run: |
          echo "database:" > config.yml
          echo "  host: \"localhost\"" >> config.yml
          echo "  port: 5434" >> config.yml
          echo "  user: \"user_test\"" >> config.yml
          echo "  password: \"password_test\"" >> config.yml
          echo "  name: \"go_bank_api\"" >> config.yml
          echo "server:" >> config.yml
          echo "  port: \"8080\"" >> config.yml
          echo "jwt:" >> config.yml
          echo "  secret_key: \"${{ secrets.JWT_SECRET_KEY }}\"" >> config.yml

      - name: Run tests
        # Env variables are still useful for other potential tools, but the primary config
        # now comes from the generated config.yml, ensuring consistency.
        env:
          # We only need to provide the secret key here now.
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
        run: go test -v ./...