# file: .github/workflows/ci.yml

name: Go Bank API CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        env:
          POSTGRES_USER: user_test
          POSTGRES_PASSWORD: password_test
          POSTGRES_DB: go_bank_api_test
        ports:
          - 5434:5432
        options: >-
          --health-cmd "pg_isready -U user_test -d go_bank_api_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.3'

      - name: Run tests
        # Environment variables for the test step.
        # We use the static credentials defined in the 'services' block above.
        # This is secure because this environment is ephemeral and destroyed after the job.
        env:
          DB_HOST: localhost
          DB_PORT: 5434
          DB_USER: user_test
          DB_PASSWORD: password_test
          DB_NAME: go_bank_api 
          JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }} # JWT Secret is still loaded securely.
          PORT: 8080
        run: go test -v ./...